version: '3.0'

services:
  app: 
    image: ayomeer/ros-devcontainer:dev-jetson
    user: "1000:1000"
    container_name: ros-container
    network_mode: host  
    volumes:
      - ..:/home/ros/proj # mount project directory

    environment:
     - DISPLAY=host.docker.internal:0.0 # set display environment to local host IP
     - MPLBACKEND=TkAgg                 # set matplotlib backend to graphics capable one

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    stdin_open: true
    tty: true