services:
  app: 
    image: ayomeer/ros-devcontainer:dev-jetson
    user: "1000:1000"
    container_name: ros-devcontainer
    working_dir: /home/ros/proj/dev_ws
    network_mode: host  

    devices: 
      - /dev/video0:/dev/video0

    volumes:
      - ..:/home/ros/proj       # mount project directory
      - /tmp/argus_socket:/tmp/argus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix # display

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] # equivalent of '--gpus=all' in docker run command

    environment:
     - DISPLAY=$DISPLAY
    
    stdin_open: true
    tty: true
